# Generated by Django 5.2.4 on 2025-07-05 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('mailchimp', 'Mailchimp'), ('zoho', 'Zoho'), ('demandbase', 'Demandbase'), ('google_ads', 'Google Ads'), ('linkedin_ads', 'LinkedIn Ads')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('draft', 'Draft')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('cpc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cpm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('cost_per_conversion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('custom', 'Custom Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('total_impressions', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_ctr', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('avg_cpc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_cpm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('cost_per_conversion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('predicted_ctr', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('predicted_conversion_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('predicted_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dashboard.campaign')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='dashboard.client'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='viewer', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_client_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dashboard.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
