# Generated by Django 5.2.4 on 2025-07-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('google_ads', 'Google Ads'), ('linkedin_ads', 'LinkedIn Ads'), ('mailchimp', 'Mailchimp'), ('zoho', 'Zoho'), ('demandbase', 'Demandbase')], max_length=20)),
                ('file', models.FileField(upload_to='client_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('processed_data', models.JSONField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='dashboard.client')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('campaign', 'Campaign Performance'), ('monthly_forecast', 'Monthly Forecast'), ('trend_analysis', 'Trend Analysis'), ('optimization', 'Optimization Recommendation')], max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('predicted_metrics', models.JSONField(default=dict)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('model_used', models.CharField(default='ensemble', max_length=50)),
                ('model_version', models.CharField(default='1.0', max_length=20)),
                ('insights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='dashboard.campaign')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='dashboard.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FutureForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_impressions', models.BigIntegerField(blank=True, null=True)),
                ('predicted_clicks', models.BigIntegerField(blank=True, null=True)),
                ('predicted_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('predicted_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('predicted_conversions', models.BigIntegerField(blank=True, null=True)),
                ('predicted_ctr', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('predicted_roi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.8, max_digits=3)),
                ('trend_direction', models.CharField(choices=[('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('trend_strength', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('seasonal_factors', models.JSONField(default=dict)),
                ('market_conditions', models.JSONField(default=dict)),
                ('risk_factors', models.JSONField(default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_forecasts', to='dashboard.client')),
            ],
            options={
                'ordering': ['-forecast_date'],
                'unique_together': {('client', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_campaigns', models.IntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_impressions', models.BigIntegerField(default=0)),
                ('total_clicks', models.BigIntegerField(default=0)),
                ('total_conversions', models.BigIntegerField(default=0)),
                ('overall_roas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_ctr', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('overall_conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('avg_cpc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_cpm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_data', models.JSONField(default=dict)),
                ('ml_insights', models.JSONField(default=dict)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='monthly_reports/')),
                ('is_generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='dashboard.client')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('client', 'month')},
            },
        ),
    ]
