# Generated by Django 5.2.4 on 2025-07-06 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_clientdataupload_mlprediction_futureforecast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='unified_data/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processed', 'Processed'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('platforms_included', models.JSONField(default=list)),
                ('processed_data', models.JSONField(blank=True, null=True)),
                ('data_summary', models.JSONField(default=dict)),
                ('insights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_data', to='dashboard.client')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('monthly_forecast', 'Monthly Forecast'), ('campaign_performance', 'Campaign Performance'), ('revenue_prediction', 'Revenue Prediction'), ('optimization', 'Optimization')], max_length=30)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('predicted_metrics', models.JSONField(default=dict)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.8, max_digits=3)),
                ('model_used', models.CharField(default='ensemble', max_length=50)),
                ('model_version', models.CharField(default='1.0', max_length=20)),
                ('insights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('risk_factors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='dashboard.client')),
                ('unified_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='dashboard.unifiedclientdata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
