# Generated by Django 5.2.4 on 2025-07-08 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_unifiedclientdata_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandbaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandbase_data', to='dashboard.client')),
            ],
        ),
    ]
