# Generated by Django 5.2.4 on 2025-07-13 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_demandbasedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('synced', 'Synced'), ('processing', 'Processing'), ('failed', 'Failed')], default='synced', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('platforms_included', models.JSONField(default=list)),
                ('data_summary', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_data', to='dashboard.client')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('client', 'date_range_start', 'date_range_end')},
            },
        ),
    ]
